const FETCH_USER = 'FETCH_USER';
const FETCH_USER_START = 'FETCH_USER_START';
const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
const FETCH_USER_FAILED = 'FETCH_USER_FAILED';
const FETCH_USER_END = 'FETCH_USER_END';

const FETCH_COMMITS_START = 'FETCH_COMMITS_START';
const FETCH_COMMITS_SUCCESS = 'FETCH_COMMITS_SUCCESS';
const FETCH_COMMITS_FAILED = 'FETCH_COMMITS_FAILED';
const FETCH_COMMITS_END = 'FETCH_COMMITS_END';
const SHOW_COMMIT_MODAL = 'SHOW_COMMIT_MODAL';
const HIDE_COMMIT_MODAL = 'HIDE_COMMIT_MODAL';
const FLASH_TYPE_ERROR = 'alert-danger';
const FLASH_TYPE_INFO = 'alert-info';
const FLASH_TYPE_WARNING = 'alert-warning';
const FLASH_TYPE_SUCCESS = 'alert-success';
const FLASH_ERROR = 'FLASH_ERROR';
const FLASH_SUCCESS = 'FLASH_SUCCESS';
const FLASH_INFO = 'FLASH_INFO';
const CLEAR_FLASH = 'CLEAR_FLASH';

/**
 * Alerts
 */
const ALERT_SUCCESS = 'alert-success';
const ALERT_DANGER = 'alert-danger';
const ALERT_WARNING = 'alert-warning';
const ALERT_INFO = 'alert-info';

/**
 * Default Texts
 */

 const DEFAULT_API_BUTTON_TITLE = "Submit"
 const DEFAULT_API_BUTTON_STYLE = "btn-primary"    


export {
    SHOW_COMMIT_MODAL, HIDE_COMMIT_MODAL,
    FETCH_USER, FETCH_USER_START, FETCH_USER_SUCCESS, FETCH_USER_FAILED,
    FETCH_USER_END, FETCH_COMMITS_START, FETCH_COMMITS_SUCCESS,
    FETCH_COMMITS_FAILED, FETCH_COMMITS_END, FLASH_TYPE_SUCCESS, FLASH_TYPE_ERROR,
    FLASH_ERROR, FLASH_SUCCESS, CLEAR_FLASH, FLASH_TYPE_WARNING, FLASH_TYPE_INFO,
    ALERT_SUCCESS, ALERT_DANGER, ALERT_WARNING, ALERT_INFO, FLASH_INFO,
    DEFAULT_API_BUTTON_TITLE, DEFAULT_API_BUTTON_STYLE
}