const FETCH_USER = 'FETCH_USER';
const FETCH_USER_START = 'FETCH_USER_START';
const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
const FETCH_USER_FAILED = 'FETCH_USER_FAILED';
const FETCH_USER_END = 'FETCH_USER_END';

const FETCH_COMMITS_START = 'FETCH_COMMITS_START';
const FETCH_COMMITS_SUCCESS = 'FETCH_COMMITS_SUCCESS';
const FETCH_COMMITS_FAILED = 'FETCH_COMMITS_FAILED';
const FETCH_COMMITS_END = 'FETCH_COMMITS_END';
const SHOW_COMMIT_MODAL = 'SHOW_COMMIT_MODAL';
const HIDE_COMMIT_MODAL = 'HIDE_COMMIT_MODAL';

export {
    SHOW_COMMIT_MODAL, HIDE_COMMIT_MODAL,
    FETCH_USER, FETCH_USER_START, FETCH_USER_SUCCESS, FETCH_USER_FAILED,
    FETCH_USER_END, FETCH_COMMITS_START, FETCH_COMMITS_SUCCESS,
    FETCH_COMMITS_FAILED, FETCH_COMMITS_END
}